[build-system]
requires = ["hatchling","hatch-vcs","hatch-pyinstaller"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/autotrios"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.pyinstaller]
require-runtime-dependencies = true
scriptname="src/autotrios/__main__.py"
name="autotrios"
loglevel="DEBUG"
add-data=["src/autotrios/data:autotrios/data"]
flags=["--onedir"]

[tool.hatch.build.hooks.vcs]
version-file = "src/autotrios/_version.py"

[tool.hatch.version]
source="vcs"

[project.scripts]
autotrios = "autotrios:__main__"
autotrios-gui= "autorios:gui"

[project]
name = "autotrios"
dynamic =["version"]
authors = [
  { name="Jan Hinrichsen", email="j.hinrichsen95@gmail.com" },
]
description = "Automate the TA Instruments Trios software and Datalogger (ARG2)"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
  "click",
  "pydantic== 1.10.8",
  "PyAutoGUI==0.9.54",
  "pywinauto==0.6.6",
  "PyQt5",
  "pyyaml",
  "pywin32",
  "platformdirs"
]