datalogger_restart: True   #this is needed for new versions of TRIOS as the 
                           #datalogger stops when a protocol is started
#workaround_Trios: True     #use internal gui specific workaround for the new
#                           # TRIOS version of HR30